const input=document.querySelector('#query'), send=document.querySelector('#send'), log=document.querySelector('#chatLog'), result=document.querySelector('#result'), welcome=document.querySelector('#welcome');
const emergency=[/боль.*груд|груд.*боль|не (могу )?дыш|задых|потер[яи].*сознани|без сознани|кровотеч|инсульт|перекос.*лиц|онемел.*рук|судорог|анафилак|сильн.*аллерг|суицид/];
const routes=[
 {keys:/упал|паден|удар|ушиб|перелом|растяж|вывих|болит.*рук|болит.*ног|голеностоп|запясть|спин.*после/,doctor:'Травматолог',level:'Сегодня',tone:'amber',text:'По описанию нужна очная оценка травматолога, чтобы исключить серьёзную травму.',next:'Если конечность деформирована, немеет или вы не можете на неё опираться — обратитесь в травмпункт без ожидания.'},
 {keys:/сып|кож|зуд|родинк|пятн|экзем|прыщ/,doctor:'Дерматолог',level:'В ближайшие дни',tone:'green',text:'Изменения кожи лучше оценить у дерматолога.',next:'Не наносите новые лечебные средства до осмотра. Если сыпь быстро распространяется, есть отёк лица или трудности с дыханием — нужна срочная помощь.'},
 {keys:/горл|кашл|насморк|температур|простуд|ухо|ангин/,doctor:'Терапевт или ЛОР',level:'В ближайшие 24–48 часов',tone:'green',text:'Первичный осмотр проведёт терапевт; при выраженной боли в ухе, горле или снижении слуха — ЛОР.',next:'Запишитесь на приём. При высокой температуре, которая плохо снижается, или затруднённом дыхании обратитесь срочно.'},
 {keys:/голов.*бол|мигрен|головокруж|онемени|спазм|памят/,doctor:'Невролог',level:'В ближайшие дни',tone:'green',text:'С такими жалобами поможет невролог, но сначала терапевт может назначить первичное обследование.',next:'Внезапная самая сильная в жизни головная боль, нарушение речи или слабость одной стороны тела — повод вызвать скорую.'},
 {keys:/живот|тошнот|рвот|изжог|понос|стул/,doctor:'Терапевт или гастроэнтеролог',level:'В течение 24 часов',tone:'amber',text:'Начните с терапевта или запишитесь к гастроэнтерологу, если симптомы повторяются.',next:'Срочно обращайтесь за помощью при резкой нарастающей боли, крови в рвоте или стуле, многократной рвоте.'}
];
function add(text,who){const el=document.createElement('div');el.className='message '+who;el.textContent=text;log.append(el);el.scrollIntoView({behavior:'smooth',block:'end'})}
function clinicCards(doctor){return `<div class="clinics"><div class="clinic"><div><strong>Городская поликлиника № 12</strong><span>${doctor} · 1,2 км · сегодня</span></div><button>Записаться</button></div><div class="clinic"><div><strong>Медицинский центр «Здоровье»</strong><span>${doctor} · 2,8 км · завтра</span></div><button>Записаться</button></div></div>`}
function showRoute(q){welcome.classList.add('hidden');add(q,'user');const lower=q.toLowerCase();let r;
 if(emergency.some(x=>x.test(lower)))r={doctor:'Экстренная медицинская помощь',level:'СРОЧНО',tone:'red',text:'В описании есть признаки, при которых нельзя ждать онлайн-консультации.',next:'Немедленно позвоните 103 или 112. Если рядом есть близкий человек, попросите его остаться с вами.'};
 else r=routes.find(x=>x.keys.test(lower))||{doctor:'Терапевт',level:'В ближайшие дни',tone:'green',text:'Терапевт проведёт первичную оценку и при необходимости направит к узкому специалисту.',next:'Запишитесь на очный приём и отметьте, когда начались симптомы и что их усиливает.'};
 setTimeout(()=>{add(`Я помогу с маршрутом. По вашему описанию рекомендую: ${r.doctor}.`,'bot');result.className='result';result.innerHTML=`<div class="triage"><span class="badge ${r.tone}">${r.level}</span><div><h3>Рекомендуемый специалист: ${r.doctor}</h3><p>${r.text}</p></div></div><div class="next"><b>Что делать:</b> ${r.next}</div>${r.tone==='red'?'':`<p><b>Ближайшие варианты записи</b></p>${clinicCards(r.doctor)}`}`;result.scrollIntoView({behavior:'smooth',block:'end'})},350)}
function submit(){const q=input.value.trim();if(!q)return;result.classList.add('hidden');input.value='';showRoute(q)}send.onclick=submit;input.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;submit()});
